\echo Creation des tables
\echo

drop table CONSTANTES;
drop table RELATION_OUVRAGE_GENRE;
drop table RELATION_OUVRAGE_AUTEUR;
drop table GENRE;
drop table AUTEUR;
drop table PRET CASCADE;
drop table UTILISATEUR;
drop table TYPE_INSCRIPTION;
drop table DOCUMENT;
drop table OUVRAGE;
drop table TYPE_DOCUMENT;
drop table BIBLIOTHEQUE;

CREATE TABLE IF NOT EXISTS CONSTANTES (
       date_courante DATE NOT NULL,
       delai_emprunt INTEGER NOT NULL CHECK (delai_emprunt > 0),
       delai_renouvellement INTEGER NOT NULL CHECK (delai_renouvellement > 0),
       max_renouvellements INTEGER NOT NULL CHECK (max_renouvellements > 0),
       max_emprunts_total INTEGER NOT NULL CHECK (max_emprunts_total > 0),
       max_emprunts_bibliotheque INTEGER NOT NULL CHECK (max_emprunts_total > 0),
       max_emprunts_dvd INTEGER NOT NULL CHECK (max_emprunts_dvd > 0),
       max_emprunts_nouveaute INTEGER NOT NULL CHECK (max_emprunts_nouveaute > 0),
       max_reservations INTEGER NOT NULL CHECK(max_reservations > 0)
);

CREATE TABLE IF NOT EXISTS BIBLIOTHEQUE (
       id_bibliotheque serial NOT NULL PRIMARY KEY, 
       nom_bibliotheque TEXT NOT NULL,
       adresse TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS OUVRAGE (
       isbn serial PRIMARY KEY NOT NULL,
       titre TEXT NOT NULL,
       sous_titre TEXT,
       langue TEXT NOT NULL,
       prix NUMERIC(5,2) NOT NULL CHECK (prix >= 0),
       annee INTEGER NOT NULL CHECK (annee > 0) 
);

CREATE TABLE IF NOT EXISTS TYPE_DOCUMENT (
       id_type_document serial NOT NULL PRIMARY KEY,
       description_type_document TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCUMENT (
       id_document serial PRIMARY KEY NOT NULL, --UNIQUE a la place de primary key
       isbn INTEGER NOT NULL REFERENCES OUVRAGE(isbn),
       id_type_document INTEGER NOT NULL REFERENCES TYPE_DOCUMENT(id_type_document),
       id_bibliotheque INTEGER NOT NULL REFERENCES BIBLIOTHEQUE(id_bibliotheque)--,
--       PRIMARY KEY (id_document,isbn)
);

CREATE TABLE IF NOT EXISTS GENRE (
       id_genre serial NOT NULL PRIMARY KEY,
       description_genre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS RELATION_OUVRAGE_GENRE (
       isbn serial NOT NULL REFERENCES Ouvrage(isbn),
       id_genre INTEGER NOT NULL REFERENCES Genre(id_genre),
       PRIMARY KEY(isbn,id_genre)
);

CREATE TABLE IF NOT EXISTS AUTEUR (
       id_auteur serial NOT NULL PRIMARY KEY,
       nom TEXT NOT NULL,
       prenom TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS RELATION_OUVRAGE_AUTEUR (
       isbn INTEGER NOT NULL REFERENCES OUVRAGE(isbn),
       id_auteur INTEGER NOT NULL REFERENCES AUTEUR(id_auteur),
       PRIMARY KEY(isbn,id_auteur)
);

CREATE TABLE IF NOT EXISTS TYPE_INSCRIPTION (
     id_type_inscription serial NOT NULL PRIMARY KEY,
     description_type_inscription TEXT NOT NULL,
     prix NUMERIC(5,2) DEFAULT(0) CHECK (prix >= 0)
);

CREATE TABLE IF NOT EXISTS UTILISATEUR (
       id_utilisateur serial UNIQUE NOT NULL,
       nom_utilisateur TEXT NOT NULL,
       prenom TEXT NOT NULL,
       age INTEGER NOT NULL CHECK (age > 7), --age minimal arbitraire pour emprunter un livre 
       email TEXT NOT NULL PRIMARY KEY,
       amende NUMERIC(10,2) NOT NULL CHECK (amende >= 0),
       id_type_inscription INTEGER NOT NULL REFERENCES TYPE_INSCRIPTION(id_type_inscription),
       date_inscription DATE NOT NULL --date d'inscription ou de renouvellement
);

CREATE TABLE IF NOT EXISTS PRET (
       id_pret serial NOT NULL PRIMARY KEY,
       id_document INTEGER NOT NULL REFERENCES DOCUMENT(id_document),
       id_utilisateur INTEGER NOT NULL REFERENCES UTILISATEUR(id_utilisateur),
       date_debut DATE NOT NULL,
       date_fin DATE NOT NULL, -- CHECK (date_fin > date_debut)
       date_rendu DATE CHECK (date_rendu >= date_debut)--,
       --PRIMARY KEY(id_document, id_utilisateur, date_debut)
);

\echo
\echo INSERTIONS
\echo

\echo
\echo INSERTION DANS LA TABLE CONSTANTES
\echo

INSERT INTO CONSTANTES VALUES (DATE(NOW()), 21, 21, 2, 40, 20, 5, 3, 5);

\echo
\echo INSERTION DANS LA TABLE BIBLIOTHEQUE
\echo

INSERT INTO BIBLIOTHEQUE VALUES (DEFAULT, 'Grand Moulin', '5 rue Thomas Mann');
INSERT INTO BIBLIOTHEQUE VALUES (DEFAULT, 'Sophie Germain', '8 place Aurélie Nemours');
INSERT INTO BIBLIOTHEQUE VALUES (DEFAULT, 'François Mitterand', 'Quai François Mauriac');

\echo
\echo INSERTION DANS LA TABLE OUVRAGE
\echo

INSERT INTO OUVRAGE VALUES (DEFAULT, 'One Piece', 'Episode 1', 'Japonnais', 9.99, 1997);
INSERT INTO OUVRAGE VALUES (DEFAULT, 'Naruto', 'Episode 5', 'Japonnais', 5.99, 1999); --1999
INSERT INTO OUVRAGE VALUES (DEFAULT, 'One Punch Man', 'Episode 11', 'Japonnais', 15.99, 2009); --2009
INSERT INTO OUVRAGE VALUES (DEFAULT, 'Cyrano de Bergerac', NULL, 'Français', 5.99, 1897); --1897
INSERT INTO OUVRAGE VALUES (DEFAULT, 'Le Petit Chaperon rouge', NULL, 'Français', 13.99, 2016); --1697

\echo
\echo INSERTION DANS LA TABLE TYPE_DOCUMENT
\echo

INSERT INTO TYPE_DOCUMENT VALUES (DEFAULT, 'LIVRE');
INSERT INTO TYPE_DOCUMENT VALUES (DEFAULT, 'CD');
INSERT INTO TYPE_DOCUMENT VALUES (DEFAULT, 'DVD');
INSERT INTO TYPE_DOCUMENT VALUES (DEFAULT, 'VHS');
INSERT INTO TYPE_DOCUMENT VALUES (DEFAULT, 'AUDIO');



\echo
\echo INSERTION DANS LA TABLE DOCUMENT
\echo

INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 1, 1); -- ONE PIECE, LIVRE, GRAND MOULIN      1
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 1, 1); -- ONE PIECE, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 1, 1); -- ONE PIECE, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 1, 1); -- ONE PIECE, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 1, 1); -- ONE PIECE, LIVRE, GRAND MOULIN      5

INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 2, 2); -- ONE PIECE, CD, SOPHIE GERMAIN    
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 2, 2); -- ONE PIECE, CD, SOPHIE GERMAIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 2, 2); -- ONE PIECE, CD, SOPHIE GERMAIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 2, 2); -- ONE PIECE, CD, SOPHIE GERMAIN 
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 2, 2); -- ONE PIECE, CD, SOPHIE GERMAIN    10

INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 3, 3); -- ONE PIECE, DVD, BFM               
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 3, 3); -- ONE PIECE, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 3, 3); -- ONE PIECE, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 3, 3); -- ONE PIECE, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 1, 3, 3); -- ONE PIECE, DVD, BFM               15

INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 1, 1); -- NARUTO, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 1, 1); -- NARUTO, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 1, 1); -- NARUTO, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 1, 1); -- NARUTO, LIVRE, GRAND MOULIN
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 1, 1); -- NARUTO, LIVRE, GRAND MOULIN         20

INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 2, 2); -- NARUTO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 2, 2); -- NARUTO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 2, 2); -- NARUTO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 2, 2); -- NARUTO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 2, 2); -- NARUTO, CD, SG                     25

INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 3, 3); -- NARUTO, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 3, 3); -- NARUTO, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 3, 3); -- NARUTO, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 3, 3); -- NARUTO, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 2, 3, 3); -- NARUTO, DVD, BFM                    30

INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 1, 1); -- ONE PUNCH MAN, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 1, 1); -- ONE PUNCH MAN, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 1, 1); -- ONE PUNCH MAN, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 1, 1); -- ONE PUNCH MAN, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 1, 1); -- ONE PUNCH MAN, LIVRE, GM              35

INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 2, 2); -- ONE PUNCH MAN, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 2, 2); -- ONE PUNCH MAN, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 2, 2); -- ONE PUNCH MAN, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 2, 2); -- ONE PUNCH MAN, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 2, 2); -- ONE PUNCH MAN, CD, SG               40

INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 3, 3); -- ONE PUNCH MAN, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 3, 3); -- ONE PUNCH MAN, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 3, 3); -- ONE PUNCH MAN, DVD, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 3, 3); -- ONE PUNCH MAN, DVD, BFM 
INSERT INTO DOCUMENT VALUES (DEFAULT, 3, 3, 3); -- ONE PUNCH MAN, DVD, BFM             45

INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 1, 1); -- CYRANO, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 1, 1); -- CYRANO, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 1, 1); -- CYRANO, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 1, 1); -- CYRANO, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 1, 1); -- CYRANO, LIVRE, GM                   50

INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 2, 2); -- CYRANO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 2, 2); -- CYRANO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 2, 2); -- CYRANO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 2, 2); -- CYRANO, CD, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 2, 2); -- CYRANO, CD, SG                      55

INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 3, 1); -- CYRANO, DVD, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 3, 1); -- CYRANO, DVD, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 3, 1); -- CYRANO, DVD, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 3, 1); -- CYRANO, DVD, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 4, 3, 1); -- CYRANO, DVD, GM                     60

INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 1, 1); -- PETIT CHAPERON ROUGE, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 1, 1); -- PETIT CHAPERON ROUGE, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 1, 1); -- PETIT CHAPERON ROUGE, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 1, 1); -- PETIT CHAPERON ROUGE, LIVRE, GM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 1, 1); -- PETIT CHAPERON ROUGE, LIVRE, GM     65

INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 4, 2); -- PETIT CHAPERON ROUGE, VHS, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 4, 2); -- PETIT CHAPERON ROUGE, VHS, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 4, 2); -- PETIT CHAPERON ROUGE, VHS, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 4, 2); -- PETIT CHAPERON ROUGE, VHS, SG
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 4, 2); -- PETIT CHAPERON ROUGE, VHS, SG       70

INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 5, 3); -- PETIT CHAPERON ROUGE, AUDIO, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 5, 3); -- PETIT CHAPERON ROUGE, AUDIO, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 5, 3); -- PETIT CHAPERON ROUGE, AUDIO, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 5, 3); -- PETIT CHAPERON ROUGE, AUDIO, BFM
INSERT INTO DOCUMENT VALUES (DEFAULT, 5, 5, 3); -- PETIT CHAPERON ROUGE, AUDIO, BFM    75

\echo
\echo INSERTION DANS LA TABLE GENRE
\echo

INSERT INTO GENRE VALUES (DEFAULT, 'DRAMATIQUE');
INSERT INTO GENRE VALUES (DEFAULT, 'FANTASTIQUE');
INSERT INTO GENRE VALUES (DEFAULT, 'ROMAN');
INSERT INTO GENRE VALUES (DEFAULT, 'AVENTURE');
INSERT INTO GENRE VALUES (DEFAULT, 'MANGA');
INSERT INTO GENRE VALUES (DEFAULT, 'HORREUR');
INSERT INTO GENRE VALUES (DEFAULT, 'COMEDIE');
INSERT INTO GENRE VALUES (DEFAULT, 'SCIENCE-FICTION');
INSERT INTO GENRE VALUES (DEFAULT, 'MERVEILLEUX');
INSERT INTO GENRE VALUES (DEFAULT, 'THRILLER');
INSERT INTO GENRE VALUES (DEFAULT, 'CONTE');

\echo
\echo INSERTION DANS LA TABLE RELATION_OUVRAGE_GENRE
\echo

INSERT INTO RELATION_OUVRAGE_GENRE VALUES (1, 5);
INSERT INTO RELATION_OUVRAGE_GENRE VALUES (1, 4);

INSERT INTO RELATION_OUVRAGE_GENRE VALUES (2, 5);
INSERT INTO RELATION_OUVRAGE_GENRE VALUES (2, 4);

INSERT INTO RELATION_OUVRAGE_GENRE VALUES (3, 5);

INSERT INTO RELATION_OUVRAGE_GENRE VALUES (4, 1);
INSERT INTO RELATION_OUVRAGE_GENRE VALUES (4, 3);

INSERT INTO RELATION_OUVRAGE_GENRE VALUES (5, 11);

\echo
\echo INSERTION DANS LA TABLE AUTEUR
\echo

INSERT INTO AUTEUR VALUES (DEFAULT, 'ODA', 'EIICHIRO');
INSERT INTO AUTEUR VALUES (DEFAULT, 'KISHIMOTO', 'MASASHI');
INSERT INTO AUTEUR VALUES (DEFAULT, 'SUZUKI', 'TOMOHIRO');
INSERT INTO AUTEUR VALUES (DEFAULT, 'MURATA', 'YUSUKE');
INSERT INTO AUTEUR VALUES (DEFAULT, 'ROSTAND', 'EDMOND');
INSERT INTO AUTEUR VALUES (DEFAULT, 'PERRAULT', 'CHARLES');

\echo
\echo INSERTION DANS LA TABLE RELATION_OUVRAGE_AUTEUR
\echo

INSERT INTO RELATION_OUVRAGE_AUTEUR VALUES (1,1);
INSERT INTO RELATION_OUVRAGE_AUTEUR VALUES (2,2);
INSERT INTO RELATION_OUVRAGE_AUTEUR VALUES (3,3);
INSERT INTO RELATION_OUVRAGE_AUTEUR VALUES (3,4);
INSERT INTO RELATION_OUVRAGE_AUTEUR VALUES (4,5);
INSERT INTO RELATION_OUVRAGE_AUTEUR VALUES (5,6);

\echo
\echo INSERTION DANS LA TABLE TYPE_INSCRIPTION
\echo

INSERT INTO TYPE_INSCRIPTION VALUES (DEFAULT, 'NORMAL', 0);
INSERT INTO TYPE_INSCRIPTION VALUES (DEFAULT, 'CD', 4.99);
INSERT INTO TYPE_INSCRIPTION VALUES (DEFAULT, 'CD / DVD', 9.99);

\echo
\echo INSERTION DANS LA TABLE UTILISATEUR
\echo

INSERT INTO UTILISATEUR VALUES (DEFAULT, 'TIRRERA', 'AMADOU', 26, 'amadou.tirrera@gmail.com', 0.00, 2, DATE(NOW()));
INSERT INTO UTILISATEUR VALUES (DEFAULT, 'DAKHLIA', 'CYRILLE', 24, 'c.dakhlia@outlook.fr', 0.00, 2, DATE(NOW()));
INSERT INTO UTILISATEUR VALUES (DEFAULT, 'JAOUANI', 'MOHAMED', 22, 'mohamed.936@hotmail.fr', 0.00, 3, DATE(NOW()));
INSERT INTO UTILISATEUR VALUES (DEFAULT, 'NASSIRI', 'LEILA', 21, 'lilia95@hotmail.fr', 0.00, 3, DATE(NOW()));
INSERT INTO UTILISATEUR VALUES (DEFAULT, 'CHABANE', 'TANIA', 22, 'tatatania@hotmail.fr', 0.00, 1, DATE(NOW()));
INSERT INTO UTILISATEUR VALUES (DEFAULT, 'COTTIN', 'KEVIN', 24, 'kevin.cottin@gmail.com', 0.00, 1, DATE(NOW()));

\echo
\echo AU DEBUT LA TABLE PRET EST VIDE
\echo
