DROP TABLE relation_hotel_service;
DROP TABLE relation_reservation_service;
DROP TABLE table_reservation;
DROP TABLE table_chambre;
DROP TABLE table_hotel;
DROP TABLE table_client;
DROP TABLE table_service;
DROP TABLE table_promotion;
DROP TYPE categorieEnum;
DEALLOCATE insertion_hotel;
DEALLOCATE insertion_reservation;
DEALLOCATE insertion_relation_hotel_service;
DEALLOCATE insertion_relation_reservation_service;
DEALLOCATE insertion_chambre;
DEALLOCATE insertion_client;
DEALLOCATE insertion_service;
DEALLOCATE insertion_promotion;
DEALLOCATE recherche_disponibilite;
DEALLOCATE reserver_creneau;
DEALLOCATE annuler_reservation_relation;
DEALLOCATE annuler_reservation;
DEALLOCATE taux_occupation_annee;
